Repository girlznight/Project-GirzDay-react-repo, pull requests merged in 2025-06, with the labels that each got.

#26 Post create
  react-project/package-lock.json
  react-project/package.json
  react-project/src/components/DraggableImage.jsx
  react-project/src/components/DraggableTextbox.jsx
  react-project/src/pages/PostCreate/PostCreate.jsx
Labels: ✨ Feature

#31 🔐 로그인한 사용자가 /login 접근 시 강제로 페이지 이동 처리 추가
  react-project/src/pages/Login/Login.jsx
  react-project/src/pages/Login/useLogin.js
Labels: 🐞 BugFix

#32 🐛 📝 Post create 중복 코드 삭제, 설명 주석 추가
  react-project/src/pages/PostCreate/PostCreate.jsx
Labels: 🐞 BugFix, 📃 Docs

#34 Post create > DragableTextbox CSS 수정
  react-project/src/components/DraggableTextbox.jsx
Labels: 🎨 Html&css
